import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  console: [{ type: "autogenerated", dirName: "console" }],
  agro: [
    { type: "autogenerated", dirName: "agro" },
    {
      type: "category",
      label: "More",
      collapsed: true,
      items: [
        "open-core",
        "model-selection",
        "glossary",
        "resources",
      ],
    },
  ],
};

export default sidebars;
